const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let token=localStorage.getItem("cc_token"), user=null, authMode="login", editingId=null;

async function api(url,opts={}){opts.headers={...(opts.headers||{}), "Content-Type":"application/json"}; if(token) opts.headers.Authorization="Bearer "+token; const r=await fetch(url,opts); const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.error||"Request failed"); return d}

function setAuth(mode){authMode=mode; $$(".tab").forEach(b=>b.classList.toggle("active",b.dataset.auth===mode)); $("#nameField").classList.toggle("hidden",mode==="login"); $("#authBtn").textContent=mode==="login"?"Login":"Create Account"; $("#password").autocomplete=mode==="login"?"current-password":"new-password"; $("#authMsg").textContent=""}
$$(".tab").forEach(b=>b.onclick=()=>setAuth(b.dataset.auth));
$("#authForm").onsubmit=async e=>{e.preventDefault();$("#authMsg").textContent="";try{const body={email:$("#email").value,password:$("#password").value};if(authMode==="signup")body.name=$("#name").value;const d=await api("/api/"+authMode,{method:"POST",body:JSON.stringify(body)});token=d.token;localStorage.setItem("cc_token",token);user=d.user;startApp()}catch(e){$("#authMsg").textContent=e.message}};
$("#logout").onclick=()=>{localStorage.removeItem("cc_token");token=null;location.reload()};

async function startApp(){if(!user)user=await api("/api/me");$("#authView").classList.add("hidden");$("#mainView").classList.remove("hidden");$("#userName").textContent=user.name;$("#roleBadge").textContent=user.role==="admin"?"ADMIN":"STUDENT";$(".admin-nav").classList.toggle("hidden",user.role!=="admin");showPage("dashboard");loadProjects();loadNotes();loadLesson("html");if(user.role==="admin")loadAdmin()}
function showPage(page){$$(".page").forEach(p=>p.classList.add("hidden"));$("#"+page).classList.remove("hidden");$$(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===page))}
$$(".nav").forEach(n=>n.onclick=()=>showPage(n.dataset.page));

async function loadProjects(){const ps=await api("/api/projects");$("#stats").innerHTML=`<div class="stat"><strong>${ps.length}</strong><span>Saved Projects</span></div><div class="stat"><strong>${new Set(ps.map(p=>p.language)).size}</strong><span>Languages Used</span></div><div class="stat"><strong>${ps.filter(p=>p.code.length>0).length}</strong><span>Projects With Code</span></div>`;$("#projectList").innerHTML=ps.length?ps.map(p=>`<div class="project"><span class="tag">${p.language.toUpperCase()}</span><h3>${esc(p.title)}</h3><p>Updated ${new Date(p.updated_at+"Z").toLocaleString()}</p><div class="project-actions"><button class="primary" onclick="openProject(${p.id})">Open</button><button class="ghost" onclick="deleteProject(${p.id})">Delete</button></div></div>`).join(""):"<div class='project'><p>No projects yet. Start your first project!</p></div>"}
async function openProject(id){const p=(await api("/api/projects")).find(x=>x.id===id);if(!p)return;editingId=id;$("#projectTitle").value=p.title;$("#language").value=p.language;$("#code").value=p.code;updateEditor();showPage("editor")}
async function deleteProject(id){if(confirm("Delete this project?")){await api("/api/projects/"+id,{method:"DELETE"});loadProjects()}}
$("#saveProject").onclick=async()=>{const body={title:$("#projectTitle").value.trim()||"Untitled Project",language:$("#language").value,code:$("#code").value};try{if(editingId)await api("/api/projects/"+editingId,{method:"PUT",body:JSON.stringify(body)});else{const d=await api("/api/projects",{method:"POST",body:JSON.stringify(body)});editingId=d.id}alert("Project saved.");loadProjects()}catch(e){alert(e.message)}};
$("#runCode").onclick=()=>runPreview();$("#language").onchange=updateEditor;function updateEditor(){const l=$("#language").value;$("#pythonInfo").classList.toggle("hidden",l!=="python");$("#preview").classList.toggle("hidden",l==="python");if(l==="html")runPreview();else if(l==="css")$("#preview").srcdoc=`<style>${$("#code").value}</style><h2>CSS Preview</h2><p>Edit CSS to see styling here.</p>`;else if(l==="javascript")$("#preview").srcdoc=`<body><h2>JavaScript Preview</h2><script>${$("#code").value.replace(/<\/script/gi,"<\\/script")}<\/script></body>`}
function runPreview(){if($("#language").value!=="html")return updateEditor();$("#preview").srcdoc=$("#code").value}

const lessons={
html:{title:"HTML — Structure of a Web Page",intro:"HTML creates the structure and content of a webpage.",items:[["Basic structure","<code>&lt;!doctype html&gt;</code>, <code>&lt;html&gt;</code>, <code>&lt;head&gt;</code>, and <code>&lt;body&gt;</code> form the foundation."],["Text","Use <code>&lt;h1&gt;</code>–<code>&lt;h6&gt;</code> for headings and <code>&lt;p&gt;</code> for paragraphs."],["Links & Images","Use <code>&lt;a href=\"...\"&gt;</code> for links and <code>&lt;img src=\"...\" alt=\"...\"&gt;</code> for images."],["Lists","Use <code>&lt;ul&gt;</code> with <code>&lt;li&gt;</code> for unordered lists and <code>&lt;ol&gt;</code> for ordered lists."]]},
css:{title:"CSS — Style Your Web Page",intro:"CSS controls colors, spacing, layout, typography and responsive design.",items:[["Selectors","Target elements with <code>p</code>, classes such as <code>.card</code>, or IDs such as <code>#header</code>."],["Box model","Learn <code>margin</code>, <code>border</code>, <code>padding</code>, and <code>width/height</code>."],["Flexbox","Use <code>display:flex</code> for one-dimensional layouts and alignment."],["Responsive design","Use <code>@media</code> queries to adapt layouts for mobile and desktop."]]},
javascript:{title:"JavaScript — Make Pages Interactive",intro:"JavaScript adds logic, events, dynamic content and application behavior.",items:[["Variables","Use <code>let</code> and <code>const</code> to store values."],["Functions","Functions group reusable logic: <code>function greet(name){ return \"Hello \"+name; }</code>."],["DOM","Use <code>document.querySelector()</code> to select HTML elements and change them."],["Events","Use <code>element.addEventListener('click', ...)</code> to respond to user actions."]]},
python:{title:"Python — Learn Programming",intro:"Python is beginner-friendly and useful for automation, data, AI and backend development.",items:[["Variables","Example: <code>name = \"Ravi\"</code> and <code>age = 15</code>."],["Conditions","Use <code>if</code>, <code>elif</code>, and <code>else</code> to make decisions."],["Loops","Use <code>for</code> and <code>while</code> to repeat work."],["Functions","Define reusable code with <code>def</code>: <code>def add(a,b): return a+b</code>."]]}}
function loadLesson(key){const l=lessons[key];$("#lesson").innerHTML=`<div class="lesson-card"><h2>${l.title}</h2><p>${l.intro}</p></div>`+l.items.map(x=>`<div class="lesson-card"><h2>${x[0]}</h2><p>${x[1]}</p></div>`).join("");$$(".learn").forEach(b=>b.classList.toggle("active",b.dataset.learn===key))}
$$(".learn").forEach(b=>b.onclick=()=>loadLesson(b.dataset.learn));

async function loadNotes(){const ns=await api("/api/notes");$("#notesList").innerHTML=ns.length?ns.map(n=>`<div class="note"><h3>${esc(n.title)}</h3><p>${esc(n.content).slice(0,180)}</p><div class="project-actions"><button class="primary" onclick="editNote(${n.id},${JSON.stringify(n.title)},${JSON.stringify(n.content)})">Edit</button><button class="ghost" onclick="deleteNote(${n.id})">Delete</button></div></div>`).join(""):"<div class='note'><p>No notes yet.</p></div>"}
$("#newNote").onclick=async()=>{const title=prompt("Note title:","Learning Note");if(title===null)return;const content=prompt("Write your note:","");if(content===null)return;await api("/api/notes",{method:"POST",body:JSON.stringify({title,content})});loadNotes()}
async function editNote(id,title,content){const nt=prompt("Note title:",title);if(nt===null)return;const nc=prompt("Note content:",content);if(nc===null)return;await api("/api/notes/"+id,{method:"PUT",body:JSON.stringify({title:nt,content:nc})});loadNotes()}
async function deleteNote(id){if(confirm("Delete note?")){await api("/api/notes/"+id,{method:"DELETE"});loadNotes()}}

async function loadAdmin(){if(user.role!=="admin")return;const [st,ps]=await Promise.all([api("/api/students"),api("/api/projects")]);$("#adminStats").innerHTML=`<div class="stat"><strong>${st.length}</strong><span>Students</span></div><div class="stat"><strong>${ps.length}</strong><span>Total Projects</span></div><div class="stat"><strong>${ps.filter(p=>p.language==="python").length}</strong><span>Python Projects</span></div>`;$("#students").innerHTML=st.map(s=>`<div class="student"><b>${esc(s.name)}</b><br><small>${esc(s.email)}</small><br><span class="tag">${s.project_count} projects</span></div>`).join("")||"<p>No students.</p>";$("#adminProjects").innerHTML=ps.map(p=>`<div class="admin-project"><b>${esc(p.title)}</b> <span class="tag">${p.language.toUpperCase()}</span><p>${esc(p.student_name)} · ${esc(p.student_email)}</p><pre>${esc(p.code)}</pre></div>`).join("")||"<p>No projects.</p>"}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
if(token){api("/api/me").then(u=>{user=u;startApp()}).catch(()=>{localStorage.removeItem("cc_token");token=null})}
